services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: startrider-api
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - mysqldb
      - rabbitmq
    networks:
      - public-network
      - private-network
    restart: always
  
  mysqldb:
    image: mysql:8.3-oracle
    container_name: mysqldb-startrider
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: StartRiderDb
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_startrider_api_volume:/var/lib/mysql
    restart: always
    networks:
      - private-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p=root" ]
      interval: 15s
      timeout: 30s
      retries: 5
  
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-startrider
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - private-network
  
  
networks:
  public-network:
    driver: bridge
  private-network:
    driver: bridge
    
volumes:
  db_startrider_api_volume:
    